version: '3.8'
services:
  postgres:
    container_name: tenant-service-postgres
    image: postgres:16
    environment:
      POSTGRES_DB: beavertenantservicedb
      POSTGRES_USER: beaveruser
      POSTGRES_PASSWORD: beaverpassword
    ports:
      - "5433:5432"
    volumes:
      - data_beaver_tenant_service_db:/var/lib/postgresql/data

  redis:
    container_name: tenant-service-redis
    image: redis:7
    ports:
      - "6380:6379"
    volumes:
      - data_beaver_tenant_service_redis:/data

volumes:
  data_beaver_tenant_service_db:
  data_beaver_tenant_service_redis: